### ISSUE TITLE
(JS-0239) Consider using `let` or `const` instead of `var`

### ISSUE THREAD

**Issue by Otherwa** [Otherwa/Sasta-Attendence#9]
## Description
It is recommended to use `let` or `const` over `var`. This will help prevent re-declaration of variables that are in the global scope when using `var`.

## Occurrences
There are 12 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/Otherwa/Sasta-Attendence/issue/JS-0239/occurrences/](https://app.deepsource.com/gh/Otherwa/Sasta-Attendence/issue/JS-0239/occurrences/)

**Comment by Shubhvrat** [comment]
Changes done.
